# Generated by Django 4.0.6 on 2022-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
